all:
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_user: admin
    ansible_password: "{{ vault_device_password }}"
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: "{{ vault_enable_password }}"

  children:
    routers:
      hosts:
        hq-router:
          ansible_host: 172.16.0.1
          ospf_router_id: 1.1.1.1
          ospf_area: 0
          site: hq
        branch-a-router:
          ansible_host: 172.16.0.2
          ospf_router_id: 2.2.2.2
          ospf_area: 1
          site: branch_a
        branch-b-router:
          ansible_host: 172.16.0.3
          ospf_router_id: 3.3.3.3
          ospf_area: 2
          site: branch_b

    switches:
      hosts:
        hq-switch:
          ansible_host: 172.16.0.10
          site: hq
        branch-a-switch:
          ansible_host: 172.16.0.11
          site: branch_a
        branch-b-switch:
          ansible_host: 172.16.0.12
          site: branch_b
